name: qwenvl
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==14.4.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.6.0
      - decorator==5.2.1
      - decord==0.6.0
      - deepspeed==0.16.4
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - dotenv==0.9.9
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - filelock==3.18.0
      - flash-attn==2.7.4.post1
      - fonttools==4.59.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.40.3
      - google-genai==1.30.0
      - gradio==3.36.1
      - gradio-client==0.2.9
      - h11==0.16.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.31.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.0
      - json-repair==0.44.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.7
      - linkify-it-py==2.0.3
      - lmdb==1.7.3
      - markdown-it-py==2.2.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - narwhals==2.1.2
      - networkx==3.2.1
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.99.9
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.11.2
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - portalocker==3.2.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==6.31.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.1.0
      - rpds-py==0.27.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.47.2
      - sty==1.0.6
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tiktoken==0.11.0
      - timeout-decorator==0.5.0
      - timm==1.0.19
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.2.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.4.0
      - uvicorn==0.35.0
      - validators==0.35.0
      - wandb==0.19.11
      - wcwidth==0.2.13
      - websockets==15.0.1
      - xlsxwriter==3.2.5
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.21.0
prefix: /mnt/petrelfs/wangziqin/lib/anaconda3/envs/qwenvl
